version: "3.9"

services:
  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ProcessToolsDB
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password123
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  mysql:
    image: mysql:8.3
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: ProcessToolsDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$password123"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  mysql-test:
    image: mysql:8.3
    container_name: mysql-db-test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: ProcessToolsDB_Test
      MYSQL_USER: admin
      MYSQL_PASSWORD: password123
    ports:
      - "3307:3306"
    volumes:
      - mysql_test_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$password123"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: admin
      PMA_PASSWORD: password123
    depends_on:
      - mysql

volumes:
  mysql_data:
  mysql_test_data:
